export {default as Banner} from "./Banner"
export {default as Story} from "./Story"
export {default as Features} from "./Features"
export {default as Steps} from "./Steps"
export {default as Requirements} from "./Requirements"
export {default as Contact} from "./Contact"
